CREATE TABLE IF NOT EXISTS `hashnut_merchants` (
  `customer_id` VARCHAR(255) NOT NULL PRIMARY KEY,
  `user_id` bigint(20) DEFAULT NULL,
  `name` VARCHAR(255) DEFAULT NULL,
  `api_key` VARCHAR(255) NOT NULL,
  `api_secret` VARCHAR(255) NOT NULL,
  `ORDER_CALLBACK_URL` VARCHAR(1000) NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `hashnut_otc_orders` (
  `id` char(36) NOT NULL,
  `pair` varchar(20) NOT NULL,
  `user_id` char(36) NOT NULL,
  `side` enum('BUY','SELL') NOT NULL,
  `quantity` decimal(65,8) NOT NULL,
  `price_id` char(36) NOT NULL,
  `create_time` bigint DEFAULT NULL,
  `expire_time` bigint DEFAULT NULL,
  `status` enum('CREATED','EXPIRED','USER_CONFIRMED','FAILED','BALANCE_DEDUCTING','BALANCE_DEDUCTED','SETTLING','SETTLED') DEFAULT 'CREATED',
  `notification_sent` tinyint(1) DEFAULT '0',
  `notification_sent_timestamp` datetime(6) DEFAULT NULL,
  `client_order_id` char(64) DEFAULT NULL,
  `price` decimal(65,8) NOT NULL,
  `stage1_operator` char(32) DEFAULT NULL,
  `stage2_operator` char(32) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_user_pair` (`user_id`,`pair`),
  KEY `idx_status` (`status`),
  KEY `idx_create_time` (`create_time`),
  KEY `idx_expire_time` (`expire_time`),
  KEY `price_id` (`price_id`),
  CONSTRAINT `online_otc_orders_ibfk_1` FOREIGN KEY (`price_id`) REFERENCES `otc_pricing` (`id`)
);

CREATE TABLE IF NOT EXISTS `otc_pricing` (
  `id` char(36) NOT NULL,
  `pair` varchar(10) NOT NULL,
  `buy_price` decimal(65,8) NOT NULL,
  `sell_price` decimal(65,8) NOT NULL,
  `timestamp` bigint DEFAULT NULL,
  `expire_timestamp` bigint DEFAULT NULL,
  `source` varchar(50) DEFAULT 'B2C2',
  PRIMARY KEY (`id`),
  KEY `idx_pair_timestamp` (`pair`,`timestamp`),
  KEY `idx_pair_expire_timestamp` (`pair`,`expire_timestamp`),
  KEY `idx_timestamp` (`timestamp`)
);

CREATE TABLE IF NOT EXISTS `users` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `username` char(32) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `unverified_email` varchar(255) DEFAULT NULL,
  `password_hash` varchar(64) NOT NULL,
  `password_method` varchar(20) NOT NULL,
  `password_salt` varchar(64) NOT NULL,
  `password_last_update` datetime(6) DEFAULT CURRENT_TIMESTAMP(6),
  `one_time_pass` char(16) DEFAULT NULL,
  `otp_confirmed` tinyint(1) DEFAULT NULL,
  `failed_login_attempts` int(11) DEFAULT '0',
  `last_login_attempt` datetime(6) DEFAULT NULL,
  `email_token` varchar(64) DEFAULT NULL,
  `email_token_expires` datetime(6) DEFAULT NULL,
  `email_token_role` char(16) DEFAULT NULL,
  `lang` char(16) DEFAULT NULL,
  `timezone` varchar(255) DEFAULT NULL,
  `type` smallint(6) DEFAULT '1',
  `api_pass` varchar(64) DEFAULT NULL,
  `referee` varchar(128) DEFAULT NULL,
  `country` varchar(32) DEFAULT NULL,
  `region` varchar(32) DEFAULT NULL,
  `trade_enabled` tinyint(1) NOT NULL DEFAULT '3',
  `deposit_enabled` tinyint(1) NOT NULL DEFAULT '1',
  `fingerprint` varchar(255) DEFAULT NULL,
  `browser` mediumtext,
  `ip_address` varchar(255) DEFAULT NULL,
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `first_name` varchar(64) DEFAULT NULL,
  `last_name` varchar(64) DEFAULT NULL,
  `referer_header` mediumtext,
  `withdraw_enabled` tinyint(1) NOT NULL DEFAULT '1',
  `iphub_block` int(11) DEFAULT NULL,
  `iphub_country` varchar(32) DEFAULT NULL,
  `iphub_info` mediumtext,
  `phone_number` varchar(20) DEFAULT NULL,
  `organisation_id` int(32) DEFAULT NULL,
  `kyc_passed` tinyint(1) DEFAULT '0',
  `doc_confirmed` tinyint(1) DEFAULT '0',
  `us_taxpayer` tinyint(1) DEFAULT '0',
  `oauth_method` varchar(255) DEFAULT NULL,
  `oauth_id` varchar(255) DEFAULT NULL,
  `account_token` varchar(80) DEFAULT NULL,
  `frozen` tinyint(1) DEFAULT '0',
  `deposited` tinyint(1) DEFAULT NULL,
  `traded` tinyint(1) DEFAULT NULL,
  `pn_add_time` datetime(6) DEFAULT NULL,
  `kyc_passed_time` datetime(6) DEFAULT NULL,
  `kyc_enable` tinyint(1) DEFAULT '1',
  `entity` char(8) DEFAULT NULL,
  `account_no` varchar(256) DEFAULT NULL,
  `ftf` tinyint(1) DEFAULT '0',
  `fullName` varchar(512) DEFAULT NULL,
  `aliases` varchar(512) DEFAULT NULL,
  `sex` enum('M','F') DEFAULT NULL,
  `countryOfBirth` varchar(64) DEFAULT NULL,
  `countryOfResidence` varchar(64) DEFAULT NULL,
  `province` varchar(64) DEFAULT NULL,
  `city` varchar(64) DEFAULT NULL,
  `address` varchar(256) DEFAULT NULL,
  `address2` varchar(128) DEFAULT NULL,
  `zip` varchar(32) DEFAULT NULL,
  `dob` date DEFAULT NULL,
  `nationality` varchar(64) DEFAULT NULL,
  `occupation` varchar(64) DEFAULT NULL,
  `industry` varchar(64) DEFAULT NULL,
  `annualIncome` decimal(20,2) DEFAULT NULL,
  `sourceWealth` varchar(128) DEFAULT NULL,
  `yearsOfEducation` decimal(3,1) DEFAULT NULL,
  `netWorth` decimal(20,2) DEFAULT NULL,
  `monthlyTradeAmount` decimal(20,2) DEFAULT NULL,
  `annualTradeFrequency` varchar(64) DEFAULT NULL,
  `cryptoUnderstanding` varchar(512) DEFAULT NULL,
  `USTaxpayer` tinyint(1) DEFAULT NULL,
  `USSocialSecurityNo` char(9) DEFAULT NULL,
  `uuid` char(36) DEFAULT NULL,
  `riskCategory` enum('LOW_RISK','MEDIUM_RISK','HIGH_RISK') DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `username` (`username`),
  UNIQUE KEY `email` (`email`),
  UNIQUE KEY `unverified_email` (`unverified_email`),
  UNIQUE KEY `phone_number` (`phone_number`),
  UNIQUE KEY `oauth` (`oauth_method`,`oauth_id`),
  KEY `email_token` (`email_token`),
  KEY `referee` (`referee`),
  KEY `account_token` (`account_token`),
  KEY `entity_idx` (`entity`),
  KEY `kyc_enable_idx` (`kyc_enable`),
  KEY `kyc_passed_idx` (`kyc_passed`),
  KEY `create_time` (`create_time`),
  KEY `first_name` (`first_name`),
  KEY `last_name` (`last_name`),
  KEY `nationality_idx` (`nationality`),
  KEY `countryOfResidence_idx` (`countryOfResidence`),
  KEY `doc_confirmed_idx` (`doc_confirmed`),
  KEY `uuid_idx` (`uuid`),
  KEY `org_idx` (`organisation_id`),
  KEY `account_no` (`account_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `user_deposit_address` (
  `id` int NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) DEFAULT NULL,
  `currency` char(32) NOT NULL,
  `address` char(128) DEFAULT NULL,
  `create_time` datetime(6) DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  KEY `user_address` (`user_id`, `currency`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
